services:
  app:
    build: .
    ports:
      - "65069:65069"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B@kawanMR11T2024
      POSTGRES_DB: ticketing_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: