version: '3.8'

services:
  app:
    build: .
    container_name: ticketing-system
    ports:
      - "65069:65069"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:17
    container_name: idiyanale-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketing_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: